export const MAX_IDENTIFIER_CODE_POINTS = 128;
export const MAX_TEXT_CODE_POINTS = 16_384;
export const MAX_JSON_DEPTH = 8;
export const MAX_OBJECT_PROPERTIES = 200;
export const MAX_ARRAY_LENGTH = 500;
export const MAX_SERIALIZED_BYTES = 64 * 1024;

export const MAX_JSON_POINTER_CODE_POINTS = MAX_TEXT_CODE_POINTS;
export const MAX_STATE_PATCH_OPERATIONS = MAX_ARRAY_LENGTH;
